# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "timetrack"
version = "0.1.0"
authors = ["ton1 <torstein.nordgard-hansen@nordicsemi.no>"]
edition = "2018"

[lib]
name = "timetrack"

[[bin]]
name = "timetrack"


[dependencies]
clap = { version = "2.33", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2.1"
dirs = "3.0"
dialoguer = "0.8"
